import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, route1, route2 }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {route1}
        {children}
        {route2}
      </body>
    </html>
  );
}
